name: compilecheck

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  native-headers:
    runs-on: ubuntu-latest # single os smoke test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Generate ucore3dall.hpp
        run: |
          python3 .scripts/GenerateuCore3DAll.py

      - name: Compile umbrella header with C++17
        run: |
          chmod +x .scripts/HeaderCompile.sh
          .scripts/HeaderCompile.sh
